### ISSUE TITLE
Move to Flux v2 (or managed flux addon)

### ISSUE THREAD

**Issue by ckittel** [mspnp/aks-baseline#144]
GitOps is working towards becoming a supported managed addon.  We should either migrate to Flux 2 OR the managed addon.  Depending on the timing.  Currently we're at the latest version of Flux v1.

**Comment by thepaulmacca** [comment]
Is there any update on this? Flux v1 is now in maintenance mode:

![image](https://user-images.githubusercontent.com/41340540/135827810-e9bdf240-7fbb-44a8-bfff-8bfb9a197362.png)

I don't see any recent updates on the GitOps add-on, but this should really be using Flux v2 moving forwards

**Comment by ckittel** [comment]
I'm hopeful that by the end of October we'll either have moved to v2 from the upstream project or to the add-on (which was delayed due to being rewritten for v2).  If you're looking for implementation of v2, we have it on [AKS Baseline for Regulated](https://github.com/mspnp/aks-baseline-regulated/tree/main/cluster-manifests/flux-system).  I'm hopeful we can just do the work once and move to the v2-based addon in a few weeks vs going to v2 only to replace it with the addon a bit later.

**Comment by thepaulmacca** [comment]
That makes sense, thanks

**Comment by thepaulmacca** [comment]
I don't suppose there's any updates on the GitOps add-on yet?

**Comment by ckittel** [comment]
The new add-on is still in private preview.  We have an exploratory story in our upcoming sprint (starting Monday).  Chances are we'll be doing that exploring in a branch here, but until it comes into public preview we cannot merge.  I'll ping you once that branch has meaningful content in it so you can see what that might look like in this situation.

One thing known for sure is that it'll require a few more egress firewall rules based on how configuration is stored as a `Microsoft.KubernetesConfiguration/fluxConfigurations` resource and the services that support the fetching/syncing of those resources manifesting themselves in your cluster.

**Comment by thepaulmacca** [comment]
That's great, thanks for the update!

**Comment by ckittel** [comment]
A rough preview of this is available @ #256 and specifically on `flux-v2-addon` branch.  Since the preview is still shaping up, we are NOT about to merge this in of course.  But looking at it might give you a sense of things to come.  Of course there is exactly NO support for anything in there at this time and no expectations of the infrastructure functioning or processes being fully/meaningfully observable at this time.

**Comment by thepaulmacca** [comment]
Ooh nice thanks for the update, will take a look!

**Comment by thepaulmacca** [comment]
I can see this is now in public preview - [docs](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2)

I've decompiled the `cluster-stamp.json` template into a bicep file, but when deploying I'm getting a `404 - Page Not Found` error

I can't find any docs on the `Microsoft.ContainerService/managedClusters/providers/extensions@2021-09-01` resource provider. I've checked the REST API docs and it doesn't seem to exist

This is what I've tried:

```bicep
  resource microsoftFluxExtension 'extensions' = {
    name: 'flux'
    properties: {
      extensionType: 'Microsoft.Flux'
      autoUpgradeMinorVersion: true
      releaseTrain: 'Stable'
      scope: {
        cluster: {
          releaseNamespace: 'flux-system'
          configurationSettings: {
            'helm-controller.enabled': 'true'
            'source-controller.enabled': 'true'
            'kustomize-controller.enabled': 'true'
            'notification-controller.enabled': 'true'
            'image-automation-controller.enabled': 'false'
            'image-reflector-controller.enabled': 'false'
          }
          configurationProtectedSettings: {}
        }
      }
    }
    dependsOn: [
      aksCluster
    ]
  }
```

```bicep
resource microsoftKubernetesConfigurationFluxExtension 'Microsoft.ContainerService/managedClusters/providers/extensions@2021-09-01' = {
  scope: aksCluster
  name: '${clusterName}/Microsoft.KubernetesConfiguration/flux'
  properties: {
    extensionType: 'Microsoft.Flux'
    autoUpgradeMinorVersion: true
    releaseTrain: 'Stable'
    scope: {
      cluster: {
        releaseNamespace: 'flux-system'
        configurationSettings: {
          'helm-controller.enabled': 'true'
          'source-controller.enabled': 'true'
          'kustomize-controller.enabled': 'true'
          'notification-controller.enabled': 'true'
          'image-automation-controller.enabled': 'false'
          'image-reflector-controller.enabled': 'false'
        }
        configurationProtectedSettings: {}
      }
    }
  }
  dependsOn: [
    aksCluster
  ]
}
```
I'm also going to raise a support ticket, but is this working for you at the moment?

**Comment by ckittel** [comment]
Yeah, last I checked, the `managedClusters` extensions resourcees have not yet been documented.  But I haven't checked in a couple of weeks.  The sub resources are as follows:

- `/subscriptions/<name>/resourceGroups/<name>/providers/Microsoft.ContainerService/ManagedClusters/<name>/providers/Microsoft.KubernetesConfiguration/extensions/flux`
- `/subscriptions/<name>/resourceGroups/<name>/providers/Microsoft.ContainerService/managedClusters/<name>/providers/Microsoft.KubernetesConfiguration/fluxConfigurations/<name>`

So there is a chance that your resource naming isn't quite right.  My bicepfoo isn't strong yet, so I might be missing how the provider identifier and name interface in this wildly-deep resource id.

**Comment by thepaulmacca** [comment]
Ah right ok I'll give that a try, appreciate your help!

**Comment by thepaulmacca** [comment]
Struggling with this without the `managedClusters` extensions resources docs. For something that's now in public preview, shouldn't this be available now? Do you know when it'll be posted?

**Comment by ckittel** [comment]
I do not know any timelines for when documentation for the API it will be posted on the Microsoft docs site, but the [schema is published](https://github.com/Azure/azure-resource-manager-schemas/blob/main/schemas/2022-01-01-preview/Microsoft.KubernetesConfiguration.json), and the docs site usually just pulls from the schema text.

**Comment by thepaulmacca** [comment]
Thanks I'll look at that and see if I can get something going

**Comment by ngbrown** [comment]
How should one bootstrap with a private git+https repo? Only `localAuthRef` is available in the config with no example on how to use it. Can you inject K8S secrets as part of the bootstrap?

**Comment by thepaulmacca** [comment]
It would be good to have some more details on the `Microsoft.KubernetesConfiguration/fluxConfigurations` resource as when querying the `apiVersions` I'm getting:

- 2021-11-01-preview
- 2021-06-01-preview

But there's nothing for either in the REST API docs
