### ISSUE TITLE
APPGW  with managed identity  doesn't support  Key Vault in in “Azure role-based access control” mode

### ISSUE THREAD

**Issue by DreamRivulet** [mspnp/aks-baseline#262]
There is a limitation:   [1395919](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1395919) that appgw can't access  Key Vault  in “Azure role-based access control” mode.  We did many tests and all failed with the same error.

It seems that it's this PR  [241](https://github.com/mspnp/aks-secure-baseline/pull/241) which changed to use Key Vault  in “Azure role-based access control” mode.

Please temporarily rollback as it doesn't work...

**Comment by DreamRivulet** [comment]
@ckittel

**Comment by ckittel** [comment]
I'm not sure I follow. The deployment here works end to end. Is this a portal experience limitation that you are seeing? Or are you seeing specific runtime functionality problems? If so, can you list the scenario in which this is causing a runtime issue; it's possible we missed a case while testing.

**Comment by DreamRivulet** [comment]
we tried to deploy this baseline script several times, all failed with the same error:

{
    "status": "Failed",
    "error": {
        "code": "ApplicationGatewayKeyVaultSecretException",
        "message": "Problem occured while accessing and validating KeyVault Secrets associated with Application Gateway '/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/applicationGateways/apw-aks-vqlhydgrlc7dw'. See details below:",
        "details": [
            {
                "code": "ApplicationGatewayTrustedRootCertificateInvalidData",
                "message": "Data for certificate /xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/applicationGateways/apw-aks-vqlhydgrlc7dw/trustedRootCertificates/root-cert-wildcard-aks-ingress is invalid."
            }
        ]
    }
}

**Comment by ckittel** [comment]
> Data for certificate /xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/applicationGateways/apw-aks-vqlhydgrlc7dw/trustedRootCertificates/root-cert-wildcard-aks-ingress is invalid.

That message makes it sound more related to what's in kv vs an access issue to kv. When you moved to access policies did the exact same key value work for you?

**Comment by scaswell-hirez** [comment]
> "Data for certificate /xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/applicationGateways/apw-aks-vqlhydgrlc7dw/trustedRootCertificates/root-cert-wildcard-aks-ingress is invalid."

I received this error message when the certificate inside the KV was not a root certificate.  If you are not using self signed certificates (a good thing :) you're likely not uploading your root cert to the key vault.

**Comment by ckittel** [comment]
We just tested this solution end to end today, and there were no issues with AppGW + KeyVault using exclusively Azure RBAC with the AppGW's managed identity for any of it.  As @scaswell-hirez mentioned, check to make sure that the certs you're using are well-formed as AppGW is expecting them.  We cannot support any instructions outside of the ones we have listed, but if there are any additional quality of life changes we can make for those that venture out past the instructions, I'm eager to add them to help anyone avoid issues. Let me know what you'd like to see added as guidance to support the situation you currently find yourself in.

**Comment by ckittel** [comment]
We just performed multiple end-to-end runs over the last couple of days with no issues as it relates to this thread :(  As mentioned above, check out the suggestion by @scaswell-hirez -- as I'm suspecting they are on the right path with that suggestion.

I'm going to close the issue at this point, but feel free to open this or another one if there is more clarity we can add anywhere in the walkthrough to prevent future issues.
