### ISSUE TITLE
AKS fails to deploy

### ISSUE THREAD

**Issue by scaswell-hirez** [mspnp/aks-baseline#264]
**Bug:**
Script cluster-stamp.json fails to deploy AKS properly and creates a chain of deployment failures in event grid, metrics, and role assignments.

**Expected Result:**
The AKS cluster deploys correctly and doesn't cause a chain of deployment failures.

**Actual Result:**
When deploying the AKS Cluster as described in https://github.com/mspnp/aks-secure-baseline/blob/main/05-aks-cluster.md it will randomly(?) fail to deploy causing all subsequent deployments that depend on the AKS Cluster to be present to also fail.  Reproduction of this error is sporadic but happens about 1 out of every 5 deployments.  I believe there may be a race condition somewhere or some other kind of Azure weirdness going on.  Subsequent redployments will sometimes resolve the issue and move forward, but I often need to burn down the whole baseline and start over to move past this point.

The following are screenshots from the failed deployment from inside the portal.

![image](https://user-images.githubusercontent.com/91915937/143272127-4e89d121-b1af-4f10-8741-0ad5372aa284.png)
![image](https://user-images.githubusercontent.com/91915937/143272230-7b4b642f-d797-473f-ae3e-382bfd5cc938.png)
![image](https://user-images.githubusercontent.com/91915937/143272310-dfab5718-9990-4ef3-ba2e-5bea41b3d438.png)
![image](https://user-images.githubusercontent.com/91915937/143272389-94af68d8-4946-4f5a-912d-4abd5622c07b.png)
![image](https://user-images.githubusercontent.com/91915937/143272450-5841af8e-aa5a-469f-af04-a28bf456aadb.png)
![image](https://user-images.githubusercontent.com/91915937/143272559-cb076de0-1329-49ef-9b47-ee6a9b7d83ef.png)

The deployment-_operations.json follows:
[deployment_operations.txt](https://github.com/mspnp/aks-secure-baseline/files/7597099/deployment_operations.txt)

**Reproduction:**
Follow the steps to cleanly deploy the aks-baseline as written.

- Use self signed certs as described
- Do not follow any optional or special instructions.  This is a purely vanilla deployment.

The AKS deployment fails roughly 20% of the time.

**Comment by ckittel** [comment]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/671075/143893227-ef72f82e-c2ba-4aab-9fd2-57751f6fc6f1.png">

Is likely the reason.  If I had to guess, you did a partial delete (like you deleted the resource group containing the cluster).  The network subnets have permissions on them for the identity that was just deleted, so on a redeploy that fails to apply.  If you do a partial delete of resources that involve managed identities, make sure you remove all the role assignments to those now-deleted identities.

**Comment by scaswell-hirez** [comment]
That would make sense, but this failure was from after following all the cleanup steps in https://github.com/mspnp/aks-secure-baseline/blob/main/11-cleanup.md and then deploying again.  Over 12 hours passed between the delete and redeploy, so any changes that needed to propagate had plenty of time.  All the resource groups had been removed, the AAD users and groups, and the key-vault purged.  No policies were found starting with the cluster name.

I've had everything cleaned up for the holiday.  I'll see if it happens again today.

**Comment by ckittel** [comment]
That `Conflict` error on that specific item is 99% due to a lingering role assignment (but with a deleted managed identity).  Just commenting on that from our past experiences over the years of doing full and partial redeployments.  The error message in that conflict will usually be pretty clear about where that role assignment was trying to be applied.

**Comment by ckittel** [comment]
We just did another end-to-end today, with no issues, following the steps listed here.  How did your deployment go? Any learnings?

**Comment by ckittel** [comment]
I'm going to go ahead and close this issue for now, but still interested in any of your findings.  If you want to reopen, you're very welcome to.
