### ISSUE TITLE
App gateway subnet too small?

### ISSUE THREAD

**Issue by Justin-DynamicD** [mspnp/aks-baseline#293]
Reviewing this reference architecture, the bicep file to create the subnets in the [spoke network](https://github.com/mspnp/aks-baseline/blob/main/networking/spoke-BU0001A0008.bicep) create a /28 subnet for the app gateway, but [recommended best practices](https://docs.microsoft.com/en-us/azure/architecture/networking/guide/waf-application-gateway#define-application-gateway-subnet-size) say the minimum size should be a /26 and recommend a /24.

Does it make sense to update the deployed example to match said best practices, or is there an overriding recommendation in the scope of AKS?

**Comment by ferantivero** [comment]
thanks for raising this issue @Justin-DynamicD,

it seems we are running a bit small based on the current recommendation, and we should consider right-sizing the appgw subnet based on [this change](https://github.com/MicrosoftDocs/azure-docs/commit/a281aa000620ffce406a219e0549ed5ce6b93abd#diff-d21f682b08540bf8893f9efa18bb2c9c271fda0c5c052239bc4387aa81d7c3a0) and updating our [topology details doc for this](https://github.com/mspnp/aks-baseline-multi-region/blob/main/networking/topology.md).

**Comment by ckittel** [comment]
I've added this as a ticket to our backlog for all of our AKS baseline implementations.  Thanks @Justin-DynamicD for bringing this to our attention and @ferantivero for following up.

**Comment by Justin-DynamicD** [comment]
I appreciate the feedback!

I'm actually going through an exercise of creating a terraform module equivalent of this work (multiple modules actually) and decided this repo was a great way to validate my own research/work.  This was just one area where I found a discrepancy so figured I'd bubble it up and see if maybe I misunderstood something.

Thank you again for answering my questions!

**Comment by rscottwatson** [comment]
@Justin-DynamicD creating a terraform version of this has been on my todo list for a long time.  Are you making your repo for that public?

**Comment by ckittel** [comment]
This has been updated in the AKS baseline for regulated mspnp/aks-baseline-regulated#60.  We still have it on our backlog to apply to the AKS baseline here.  Usually, we do things like this in the AKS baseline first and then port to the "spoke" stories, but we already had some work scheduled on the other, so it made sense from work optimization perspective :)  Keeping this issue open until resolved here as well.

**Comment by ckittel** [comment]
As far as a terraform version of the AKS baseline, consider checking out [the work that our partner team has done](https://github.com/Azure/AKS-Landing-Zone-Accelerator/tree/main/Scenarios/Secure-Baseline/Terraform), where they took this repo and modeled it as a Terraform deployment.

**Comment by Justin-DynamicD** [comment]
@rscottwatson in a way, yes.  What I mean is I've broken the components up into multiple modules (thus repos)  as I'm following a code structure similar to what I've read from the MS enterprise scale CAF model (mainly splitting azure into level 0-4).  So, the networking ends up in a separate module (because id apply that at level 2) from the aks cluster (level 3).  I plan on then putting a sample module/plan together that leverages said modules in a full example.

[My networking module](https://github.com/Justin-DynamicD/terraform-azurerm-virtual_network)


[My (very in progress) AKS module](https://github.com/Justin-DynamicD/terraform-azurerm-aks_baseline)

@ckittel thank you for the link!  It's always good to see another perspective/approach on all of this.  I'll certainly go through it, especially to see how they handle the flux integration as that's been my sticking point thus far.
