### ISSUE TITLE
"The resource provision operation did not complete within the allowed timeout period." - 06-aks-cluster

### ISSUE THREAD

**Issue by jiyongseong** [mspnp/aks-baseline#295]
Hi 

I executed option #1 cli of 06-aks-cluster.
it failed after runs 2h 15 mins.

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/17041566/158739057-05c9e5bc-b412-4011-903c-3f28bd999cb3.png">

<img width="803" alt="image" src="https://user-images.githubusercontent.com/17041566/158779507-ed0efb27-77a5-44a9-839d-9db1ae8b25d7.png">

Am I missing something?

**Comment by jiyongseong** [comment]
some finding 
there is some error on the flux controller.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/17041566/158799607-5dcebc40-2ace-4e4d-b9eb-b82e850c158b.png">

**Comment by jiyongseong** [comment]
/mnt/c/Users/jyseong  k describe pod fluxconfig-controller-bd65795db-5q749                                                   ✔  at aks-vd6olm3gwnn7w/flux-system ○  at 20:44:30
Name:         fluxconfig-controller-bd65795db-5q749
Namespace:    flux-system
Priority:     0
Node:         aks-npuser01-35102025-vmss000001/10.240.0.35
Start Time:   Thu, 17 Mar 2022 19:43:34 +0900
Labels:       app.kubernetes.io/component=fluxconfig-controller
              app.kubernetes.io/name=flux-extension
              control-plane=controller-manager
              pod-template-hash=bd65795db
Annotations:  prometheus.io/port: 8080
              prometheus.io/scrape: true
Status:       Running
IP:           10.240.0.50
IPs:
  IP:           10.240.0.50
Controlled By:  ReplicaSet/fluxconfig-controller-bd65795db
Containers:
  manager:
    Container ID:   containerd://02687a279bba72c1b12ad95c10ade5fc14e208d5369ed7675d9afeecdaf25f3b
    Image:          mcr.microsoft.com/azurek8sflux/fluxconfig-controller:0.5.2
    Image ID:       mcr.microsoft.com/azurek8sflux/fluxconfig-controller@sha256:5d502a6085482f161ce5c8ec49e0e2cbc4265dbf83fc2e1c22f724872ab00a60
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 17 Mar 2022 20:43:05 +0900
      Finished:     Thu, 17 Mar 2022 20:43:14 +0900
    Ready:          False
    Restart Count:  16
    Limits:
      cpu:     100m
      memory:  150Mi
    Requests:
      cpu:     5m
      memory:  30Mi
    Environment Variables from:
      flux-extension-values  ConfigMap  Optional: false
    Environment:
      AGENT_NAME:  FluxConfigController
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-t9884 (ro)
  fluent-bit:
    Container ID:   containerd://5a515d2c2fee8816ff58b0f2e4f6adb0eab70bc1b5afb22996b338d360da9ac8
    Image:          mcr.microsoft.com/azurek8sflux/fluent-bit:0.5.2
    Image ID:       mcr.microsoft.com/azurek8sflux/fluent-bit@sha256:00ad95627ee68d003872bcfcb51f5f3104e904f83c86b68d281b0f2a69ac3dc0
    Port:           2020/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 17 Mar 2022 19:43:46 +0900
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     20m
      memory:  150Mi
    Requests:
      cpu:     5m
      memory:  50Mi
    Environment Variables from:
      flux-extension-values  ConfigMap  Optional: false
    Environment:
      POD_NAME:    fluxconfig-controller-bd65795db-5q749 (v1:metadata.name)
      AGENT_TYPE:  ConfigAgent
      AGENT_NAME:  FluxConfigController
    Mounts:
      /fluent-bit/etc/ from fluentbit-fluxextension (rw)
      /var/lib/docker/containers from varlibdockercontainers (ro)
      /var/log from varlog (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-t9884 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  varlog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:
  varlibdockercontainers:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker/containers
    HostPathType:
  fluentbit-fluxextension:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      fluxextension-fluentbit-config
    Optional:  false
  kube-api-access-t9884:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                  From     Message
  ----     ------   ----                 ----     -------
  Normal   Started  61m                  kubelet  Started container fluent-bit
  Normal   Created  60m (x4 over 61m)    kubelet  Created container manager
  Normal   Started  60m (x4 over 61m)    kubelet  Started container manager
  Normal   Pulled   59m (x4 over 61m)    kubelet  Container image "mcr.microsoft.com/azurek8sflux/fluxconfig-controller:0.5.2" already present on machine
  Warning  BackOff  89s (x268 over 61m)  kubelet  Back-off restarting failed container

**Comment by jiyongseong** [comment]
[query_data (1).csv](https://github.com/mspnp/aks-baseline/files/8299674/query_data.1.csv)

attaching logs

**Comment by ckittel** [comment]
What region did you deploy to?

This seems to happen if your cluster isn't provisioned with konnectivity.  In that case, some additional firewall rules need to be added.  I'm sorry this happened to you.  Can you test by readding the firewall rules from https://docs.microsoft.com/azure/aks/limit-egress-traffic#azure-global-required-network-rules -- specifically the 1194 & 9000 port ones.  Also, if you introduced any ACL on your API cluster, make sure your firewall egress IPs are included in that list.

**Comment by ckittel** [comment]
There is currently a known issue with the Flux v2 extension that is shipping at the time this issue was opened.  There was an assumption being made that the helm controller is enabled on the flux deployment.  That assumption is being removed from the Flux v2 extension that is currently rolling out to clusters soon.  There is another issue we are investigating with the `CriticalAddonsOnly` taint is preventing the flux controllers from starting on the cluster.  We are investigating that as well.

**Comment by ckittel** [comment]
@akulich `helm-controller.enabled` set that to `true` in the ARM template.  You can remove the `CriticalAddonsOnly` taint as well from the same ARM template.  I was hoping these fixes would have been rolled out to production by now, so didn't make the temporary change here in the repo, but I'm thinking I'm going to, with the idea of reverting once the next version is released.

I'm not aware of any way to track that specific issue, sorry @akulich.

**Comment by ckittel** [comment]
@akulich: here is a PR that should address the issue.  I have run it through testing yet, so don't want to merge incase there is a typo in there.  https://github.com/mspnp/aks-baseline/pull/298

**Comment by ckittel** [comment]
The fix for this issue is in v0.6.0 of the extension, which should be rolling out presently.

**Comment by ckittel** [comment]
The new version of Flux Extension has been rolled out to clusters (currently version 1.0.0), which makes the helm-controller problem go away that @jiyongseong and @akulich were running into.

Just a heads up that the extension does NOT tolerate the `CriticialAddonsOnly` taint, which means that if you use that taint on your system node pool, the extension will land on an available user node pool.  If all of your user node pools are also tainted, the extension will fail to deploy.  This reference implementation keeps the taint on the system node pool, in hopes that eventually the extension will tolerate that taint.  There are no taints on the user node pool.

Also, remember if you have any Azure Policies that check for requests/limits, the namespace you choose to deploy the flux extension into currently needs to be in audit (or in an exclusion) mode, as the pods currently do not have request/limits on them.
