### ISSUE TITLE
Why do the bicep templates have an @allowed list of locations?

### ISSUE THREAD

**Issue by larryclaman** [mspnp/aks-baseline#296]
Wondering why the bicep templates specifically have an allowed list of locations they can deploy to? Ran into this when I tried to deploy to westus3 and it failed because it wasn't on the list.  It was a quick fix to add westus3 to the list of allowed locations, but it made me think: why have this list at all? I see from the description that the intention is to only allow deployments to regions with AZ support (_The network team maintains this approved regional list which is a subset of zones with Availability Zone support_),  but IMHO, this is the wrong place to enforce governance.  If there is to be a list of allowed regions, then I would say that should be enforced via Azure Policy, not via an allowed list in a bicep/arm template.  Which means that when this list needs to be updated (to add westus3, for example), it needs to get updated in multiple templates versus one central policy setting.

see https://github.com/mspnp/aks-baseline/blob/f6012cb50846e265be41a08300d13a32407ee51c/networking/hub-default.bicep#L5 for an example

This

**Comment by ckittel** [comment]
Azure policy would be a great place to show this!  For a demo though, that would be hard for someone stepping through this workload to deploy to track down.  They would have to modify another template that has this allow list.  But you're right, for your situation you would be spot on to use Azure Policy for that.

The reasoning for the list was to provide a list of regions that had paired regions that contained all of the resources that we deploy in the reference architecture.  Nothing worse than trying to deploy something and it's not available in the region or paired region, and the deployment failing.  The list was originally based on availability zone support.  If there is a region + paired region that should be added to the list, we'd be glad to see it in there.

Hope that helps.
