### ISSUE TITLE
cluster-stamp.json has a default location set -- should it?

### ISSUE THREAD

**Issue by larryclaman** [mspnp/aks-baseline#297]
per 
https://github.com/mspnp/aks-baseline/blob/f6012cb50846e265be41a08300d13a32407ee51c/cluster-stamp.json#L50

it sets the default location of the deployment to 'eastus2'.  Perhaps the default should be removed.

Additionally, the example in the instructions should probably explicitly provide a location as a parameter, see
https://github.com/mspnp/aks-baseline/blob/f6012cb50846e265be41a08300d13a32407ee51c/06-aks-cluster.md?plain=1#L22

**Comment by ckittel** [comment]
Yeah, we left the default in here, but I agree that it should instead be passed in based on the spoke network's region.  That way everything flows without needing to make modifications.  Make the spoke decision once, and then it informs the rest of the decisions.  We can put this on our backlog.  Likely won't be picked up for a month, but if you happen to implement this before then, PRs welcome.  We'll keep this issue open for tracking.
