### ISSUE TITLE
aks-deploy.yaml file patching documentation issue

### ISSUE THREAD

**Issue by pallavgupta** [mspnp/aks-baseline#307]
![pipe missing](https://user-images.githubusercontent.com/11171356/166066609-9c03ecfa-32b0-46e8-8911-fbfd9fa0d857.JPG)

Document link:- https://github.com/mspnp/aks-baseline/blob/main/06-aks-cluster.md

There is a pipe missing aks-deploy.yaml patching command in documentation. Currently command is throughing an error like:

pallav@Azure:~/aks-secure-baseline$ cat github-workflow/aks-deploy.yaml | \
>     sed "s#<resource-group-location>#eastus2#g" | \
>     sed "s#<resource-group-name>#rg-bu0001a0008#g" | \
>     sed "s#<geo-redundancy-location>#centralus#g" | \
>     sed "s#<cluster-spoke-vnet-resource-id>#${RESOURCEID_VNET_CLUSTERSPOKE_AKS_BASELINE}#g" | \
>     sed "s#<tenant-id-with-user-admin-permissions>#${TENANTID_K8SRBAC_AKS_BASELINE}#g" | \
>     sed "s#<azure-ad-aks-admin-group-object-id>#${AADOBJECTID_GROUP_CLUSTERADMIN_AKS_BASELINE}#g" | \
>     sed "s#<azure-ad-aks-a0008-group-object-id>#${AADOBJECTID_GROUP_A0008_READER_AKS_BASELINE}#g" | \
>     sed "s#<domain-name>#${DOMAIN_NAME_AKS_BASELINE}#g" \
>     sed "s#<bootstrapping-repo-https-url>#${GITOPS_REPOURL}#g"
**sed: can't read sed: No such file or directory
sed: can't read s#<bootstrapping-repo-https-url>#https://github.com/pallavgupta/aks-baseline.git#g: No such file or directory
sed: couldn't write 153 items to stdout: Broken pipe**

**Comment by ckittel** [comment]
Thanks @pallavgupta for letting us know, fixed in #309 

Btw, if you're currently going through this, just be aware of a known issue that was recently introduced (a regression) that is fixed in #306 -- I'm waiting on a final review before I merge that in.

**Comment by pallavgupta** [comment]
@ckittel Thank you.
