### ISSUE TITLE
Breaking change in output of az ad signed-in-user show

### ISSUE THREAD

**Issue by ulkeba** [mspnp/aks-baseline#327]
As of [Microsoft Graph migration](https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration), the `objectId` is now stored in property `id`. Queries like, for example, in `08-workload-prerequisites.md` will need to be changed from
`az ad signed-in-user show --query 'objectId' -o tsv`
to
`az ad signed-in-user show --query 'id' -o tsv` 

This may depend on the az CLI versions.

**Comment by ckittel** [comment]
Also fixed in the AKS baseline for multi-region and AKS baseline for regulated industries.  Thanks again @ulkeba for the heads up!
