### ISSUE TITLE
Question: Azure Gov support

### ISSUE THREAD

**Issue by anwarchk** [mspnp/aks-baseline#349]
Hello 👋 

How many of the overall steps, and especially the pre-req steps do really apply to Azure Gov ?  For eg:

```
az feature register --namespace "Microsoft.ContainerService" -n "EventgridPreview"
az feature register --namespace "Microsoft.ContainerService" -n "AKS-ExtensionManager"
az feature register --namespace "Microsoft.ContainerService" -n "EnableOIDCIssuerPreview"
```
They all comeback with FeatureNotFound code. AND for this command, the only configuration of Defender for Containers never comes back from the `Registering` state

`
az feature list -o table --query "[?name=='Microsoft.ContainerService/EventgridPreview' || name=='Microsoft.ContainerService/AKS-ExtensionManager' || name=='Microsoft.ContainerService/EnableOIDCIssuerPreview' || name=='Microsoft.ContainerService/AKS-AzureDefender' ].{Name:name,State:properties.state}"
`

```
Name                                          State
--------------------------------------------  -----------
Microsoft.ContainerService/AKS-AzureDefender  Registering
```

Is there an adapted version of this setup where it is tested and proved against Azure Gov ?

**Comment by anwarchk** [comment]
@jftl6y ^^^

**Comment by anwarchk** [comment]
Just wanted to know whether it is worth going through this if I am in Azure Gov env.

**Comment by ckittel** [comment]
This has not been tested with Azure Gov, @anwarchk.  Luckily EventgridPreview and EnableOIDCIssuerPreview are no longer necessary and have been removed as of #350 and #351 

`AKS-AzureDefender` is, but looks like that one was working for you anyhow.

If you do get through the deployment, leave us a note on how it went.  No one on our team has access to Gov, so there hasn't been any testing.

**Comment by anwarchk** [comment]
Cool, trying this out again with the new updates. Will update my notes here @ckittel
