### ISSUE TITLE
Resource deployment operation failed

### ISSUE THREAD

**Issue by sbiitmc** [mspnp/aks-baseline#358]
When it comes to deploying the network hub and spokes I run into a strange issue.
Im running the code right 'out of the box' and keeps getting the error:

**$ az deployment group create -g rg-enterprise-networking-spokes -f networking/spoke-BU0001A0008.bicep -p location=eastus2 hubVnetResourceId="${RESOURCEID_VNET_HUB}"**
_{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidDeployment\",\r\n    \"message\": \"The provided deployment name 'Peer-vnet-spoke-BU0001A0008-00Tovnet-eastus2-hub\\r' has these invalid characters: '\\r'. The name can only be a letter, digit, '-', '.' or '_'. Please see https://aka.ms/arm-deploy for usage details.\"\r\n  }\r\n}"}]}}_

I cannot figure out what the problem is. Any one who can help me?

**Comment by ckittel** [comment]
Looks like somehow a carriage return (`\r`) got added to the end of your deployment name of `Peer-vnet-spoke-BU0001A0008-00Tovnet-eastus2-hub`.  That's odd!

I wonder if there is some unexpected shell interference here.  What shell/OS are you running from, maybe we can track that down?

**Comment by sbiitmc** [comment]
I have found the issue.

In this:
RESOURCEID_VNET_HUB=$(az deployment group show -g rg-enterprise-networking-hubs -n hub-default --query properties.outputs.hubVnetId.value -o tsv)
echo RESOURCEID_VNET_HUB: $RESOURCEID_VNET_HUB

The variable $RESOURCEID_VNET_HUB seems to contain an extra whitespace in the end.
To solve this I copied the echo’ed value and manually inserted it into the deployment line below without the extra whitespace.

az deployment group create -g rg-enterprise-networking-spokes -f networking/spoke-BU0001A0008.bicep -p location=eastus2 hubVnetResourceId="${RESOURCEID_VNET_HUB}"


--
  Søren B. Isaksen
***@***.***<http://itmcsoft.com/>

   m: +45 4052 3137
   in: LinkedIn<https://dk.linkedin.com/in/sorenisaksen>

Fra: Chad Kittel ***@***.***>
Sendt: 1. december 2022 22:46
Til: mspnp/aks-baseline ***@***.***>
Cc: Søren Isaksen ***@***.***>; Author ***@***.***>
Emne: Re: [mspnp/aks-baseline] Resource deployment operation failed (Issue #358)


Looks like somehow a carriage return (\r) got added to the end of your deployment name of Peer-vnet-spoke-BU0001A0008-00Tovnet-eastus2-hub. That's odd!

I wonder if there is some unexpected shell interference here. What shell/OS are you running from, maybe we can track that down?

**Comment by ckittel** [comment]
Interesting, `properties.outputs.hubVnetId.value` doesn't seem to include any extra trailing whitespace.  I wonder if your results would be different if the command executed was `az deployment group show -g rg-enterprise-networking-hubs -n hub-default --query 'properties.outputs.hubVnetId.value' -o tsv` instead (with the extra `'` in there).

I'm going to close as there isn't anything obvious to change about the bicep output, but if you do find out anything that can make the repro consistent, let me know!
