### ISSUE TITLE
Add support for entire deployment using K8s control plane with GitOps

### ISSUE THREAD

**Issue by dtzar** [mspnp/aks-baseline#359]
It would be a nice feature add to have the full deployment utilizing CAPZ plus Azure Service Operator (for parts which are missing from CAPZ) and then everything using GitOps.  Great to see some GitOps in the setup!

**Comment by ckittel** [comment]
That seems like that would be a pretty cool addition indeed.  Probably not in the general purpose AKS baseline though, as that's probably two steps further than we have in scope for our learners here.  If you'd like to reach out to me on Teams David, we could talk about what it would take to build an Azure Architecture Center contribution that tells this story and includes an implementation for users to experience it.  I'm going to close this as "won't do" (specifically for this repo), but I want to continue the convo.  HMU on teams, and we can brainstorm this.
