### ISSUE TITLE
Resource Group cannot be found when deploying the BU0001A0008 Spoke

### ISSUE THREAD

**Issue by YordivanHorck** [mspnp/aks-baseline#376]
I'm following the deployment reference implementation to deploy the AKS-baseline for my graduation project. I'm running into an issue that my lack of knowledge within azure is unable to fix.

on the step of deploying the spoke i'm running against the error that when executing it it gives me the error in the following image.
![image](https://user-images.githubusercontent.com/127207196/232726478-8bfbb5be-8031-42ab-a8ea-298ca66a8654.png)

initially we thought it might have been a policy conflict due to us not being able to deploy a AKS cluster trough a different method as well so we solved that by disabling most policy's since it is a dev environment anyway. this did not fix the issue within the deployment of the AKS-baseline. i'm assuming something is going wrong in the bicep file for the spoke deployment due to the resource group that it's trying having the name of the ID for our subscription.

if there is a way to solve this i'd appreciate the help.

**Comment by ckittel** [comment]
I just tested the code that is on `main` and was not able to reproduce your situation.  The only place that a resource group could get confused for a subscription ID would have been on line 38, as far as I can see.  But that gets the correct value in my run, and should have been in yours as well based on your output...  did you make any modifications to the bicep files over what's in `main`?


```bash
az group create -n rg-enterprise-networking-hubs -l centralus
az group create -n rg-enterprise-networking-spokes -l centralus
az deployment group create -g rg-enterprise-networking-hubs -f networking/hub-default.bicep -p location=eastus2
*success*

RESOURCEID_VNET_HUB=$(az deployment group show -g rg-enterprise-networking-hubs -n hub-default --query properties.outputs.hubVnetId.value -o tsv)
echo RESOURCEID_VNET_HUB: $RESOURCEID_VNET_HUB

az deployment group create -g rg-enterprise-networking-spokes -f networking/spoke-BU0001A0008.bicep -p location=eastus2 hubVnetResourceId="${RESOURCEID_VNET_HUB}
*success*
```

**Comment by YordivanHorck** [comment]
> I just tested the code that is on `main` and was not able to reproduce your situation. The only place that a resource group could get confused for a subscription ID would have been on line 38, as far as I can see. But that gets the correct value in my run, and should have been in yours as well based on your output... did you make any modifications to the bicep files over what's in `main`?
> 
> ```shell
> az group create -n rg-enterprise-networking-hubs -l centralus
> az group create -n rg-enterprise-networking-spokes -l centralus
> az deployment group create -g rg-enterprise-networking-hubs -f networking/hub-default.bicep -p location=eastus2
> *success*
> 
> RESOURCEID_VNET_HUB=$(az deployment group show -g rg-enterprise-networking-hubs -n hub-default --query properties.outputs.hubVnetId.value -o tsv)
> echo RESOURCEID_VNET_HUB: $RESOURCEID_VNET_HUB
> 
> az deployment group create -g rg-enterprise-networking-spokes -f networking/spoke-BU0001A0008.bicep -p location=eastus2 hubVnetResourceId="${RESOURCEID_VNET_HUB}
> *success*
> ```

I have made  0 modifications to the bicep files since we wanted to test it out with the default implementation at first.

**Comment by ckittel** [comment]
That's quite the mystery.  I don't know what else to suggest.  Have you had any luck troubleshooting?

**Comment by ckittel** [comment]
Since this has gone dark, will close.  Hope you figure it out, @YordivanHorck!

**Comment by maadityo** [comment]
adding on this thread, i had similar case, the script does not work on bash. however it worked flawlessly on powershell. 
![image](https://github.com/mspnp/aks-baseline/assets/23251706/a8553898-c83d-429e-a9af-c5781eef7388)
![image](https://github.com/mspnp/aks-baseline/assets/23251706/b03e2a42-a6a6-4034-acf9-17bd6ddb47dd)
exactly same script, so try to run on powershell if anyone encounter same issue.
