### ISSUE TITLE
Deployment warning: The property "schema" is not allowed on objects of type "ParameterDefinitionsValue"

### ISSUE THREAD

**Issue by pcgeek86** [mspnp/aks-baseline#382]
### Summary

During the cluster deployment, this error occurs:

```
C:\git\aks-baseline\nested_K8sCustomIngressTlsHostsHaveDefinedDomainSuffix.bicep(87,9) : Warning BCP037: The property "schema" is not allowed on objects of type "ParameterDefinitionsValue". Permissible properties include "allowedValues". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
```

**Comment by ckittel** [comment]
Thanks.  It is indeed just a warning, and you won't see any negative impacts from it.  There are a few of them out there, as I'm sure you saw. :)

**Comment by ckittel** [comment]
I'll leave this open as a "good first issue" if someone wants to pick this up before one of us happens to do so.

**Comment by johndowns** [comment]
Closing this one - the warning has gone away now (I think with the latest policy definition API version).
