### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by Bafff** [mspnp/aks-baseline#383]
Hi!

In the [04-networking.md](https://github.com/mspnp/aks-baseline/blob/main/04-networking.md)  I cannot open the link used: [VWAN virtual hub extension](https://learn.microsoft.com/azure/architecture/guide/networking/private-link-vwan-dns-virtual-hub-extension-pattern) by your networking team.

**Comment by michaelrsee** [comment]
@Bafff 

I replicated this issue with the resulting page returning a '404 - Page Not Found.' 

In digging into it, the original link needs to be updated to the new link for the virtual hub extension pattern.

Original Link: https://learn.microsoft.com/azure/architecture/guide/networking/private-link-vwan-dns-virtual-hub-extension-pattern

Updated Link: https://learn.microsoft.com/en-us/azure/architecture/guide/networking/private-link-virtual-wan-dns-virtual-hub-extension-pattern

**Comment by ckittel** [comment]
Good catch, thank you. I've updated to <https://learn.microsoft.com/azure/architecture/guide/networking/private-link-virtual-wan-dns-virtual-hub-extension-pattern>
