### ISSUE TITLE
ApplicationGatewayKeyVaultSecretException

### ISSUE THREAD

**Issue by Kapilg18** [mspnp/aks-baseline#392]
Hi ,

Facing this issue while running Command: 

az deployment group create -g rg-bu0001a0008 -f cluster-stamp.bicep -p targetVnetResourceId=${RESOURCEID_VNET_CLUSTERSPOKE_AKS_BASELINE} clusterAdminAadGroupObjectId=${AADOBJECTID_GROUP_CLUSTERADMIN_AKS_BASELINE} a0008NamespaceReaderAadGroupObjectId=${AADOBJECTID_GROUP_A0008_READER_AKS_BASELINE} k8sControlPlaneAuthorizationTenantId=${TENANTID_K8SRBAC_AKS_BASELINE} appGatewayListenerCertificate=${APP_GATEWAY_LISTENER_CERTIFICATE_AKS_BASELINE} aksIngressControllerCertificate=${AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64_AKS_BASELINE} domainName=${DOMAIN_NAME_AKS_BASELINE} location=centralindia

Error :

{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/[sub]/resourceGroups/rg-bu0001a0008/providers/Microsoft.Resources/deployments/cluster-stamp","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions//resourceGroups/rg-bu0001a0008/providers/Microsoft.Network/applicationGateways/apw-aks-oufhjyt6iiaoe","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"ApplicationGatewayKeyVaultSecretException","message":"Problem occured while accessing and validating KeyVault Secrets associated with Application Gateway '/subscriptions//resourceGroups/rg-bu0001a0008/providers/Microsoft.Network/applicationGateways/apw-aks-oufhjyt6iiaoe'. See details below:","details":[{"code":"0","message":"Operation returned an invalid status code 'NotFound'"}]}]}]}}

Detail Error:

{

  "code": "ApplicationGatewayKeyVaultSecretException",

  "message": "Problem occured while accessing and validating KeyVault Secrets associated with Application Gateway '/subscriptions//resourceGroups/rg-bu0001a0008/providers/Microsoft.Network/applicationGateways/apw-aks-oufhjyt6iiaoe'. See details below:",

  "details": [

    {

      "code": "0",

      "message": "Operation returned an invalid status code 'NotFound'"

    }

  ]

}

Please let me know if more details required

**Comment by johndowns** [comment]
Apologies for the slow reply on this. I think our recent changes have resolved this issue, including changing the deployment sequence slightly on a couple of resources and adopting the latest API versions.

I've deployed the baseline dozens of times recently and haven't run into this issue, so I'm going to consider it closed - but feel free to reopen if you see it again. Thanks!
