### ISSUE TITLE
The APP Gateway is failing when deploying to Azure for US Government

### ISSUE THREAD

**Issue by dguncetdci** [mspnp/aks-baseline#395]
I added a few US Government regions to the bicep and the deployment is failing
@allowed([
  'usgovvirginia'
  'usgovtexas'
  'usgovarizona'
])

Have you tested in Azure for US Government. Can we make it more generic and add the Azure for US Government regions.

**Comment by ckittel** [comment]
We have not tested it for US Government.  I see you're starting that process.  Much appreciated and we'll be curious the results.  Keep us posted.

**Comment by ckittel** [comment]
Once you have it working end to end, we'll evaluate whatever changes are necessary in one or more PRs.  We don't want to start adding allowances for regions if they are not working as expected.  Keep us posted.
