### ISSUE TITLE
why https://github.com/mspnp/aks-baseline-multi-region was deleted

### ISSUE THREAD

**Issue by EvertonSA** [mspnp/aks-baseline#430]
Hi colleagues,

may I know why https://github.com/mspnp/aks-baseline-multi-region was deleted?

I was using it as reference but I forgot to fork. can it be made available again?

**Comment by ckittel** [comment]
[aks-baseline-multi-region-main.zip](https://github.com/user-attachments/files/17015359/aks-baseline-multi-region-main.zip)

Here is the .zip from `main` at the point it was deleted.

**Comment by EvertonSA** [comment]
THANK YOU!!!
